### ISSUE TITLE
Add GSoC 2021 Proposals

### ISSUE THREAD

**Issue by NishealJ** [cdli-gh/Framework#100]
## Summary

Please collect GSoC 21 proposal from the devs + create a folder and add it here https://github.com/cdli-gh/Framework/tree/master/Proposal

Find the proposals in slack channel.

https://summerofcode.withgoogle.com/archive/2021/organizations/5679162177617920#projects-list

#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/Framework/

**Comment by epageperron** [comment]
It might be best to email the participants
