### ISSUE TITLE
Simple forum compatible with CakePHP

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/Framework#11]
Find a module, install and test it.
Integrate with our access system.

#### 📈 Progress (0-1): 0

**Comment by epageperron** [comment]
This issue was moved to cdli-gh/Framework#8

**Comment by jayanthjaiswal** [comment]
@epageperron  Just use [Forum module](https://www.drupal.org/docs/8/core/modules/forum/overview). I am already using [that in my website](https://people.stanford.edu/jayanthj/generic-forum). The module is easy to use and configure. It requires the modules Node, History, Taxonomy, Comment and Options, which generally is enabled on most Drupal sites except Comment.

**Comment by epageperron** [comment]
We use in Drupal 7, it doesn't do what we need. We have to test it on Drupal 8!
(You are literally on a spree! :)

**Comment by epageperron** [comment]
So far the Drupal 8 forum looks exactly like the drupal 7 forum :/

**Comment by epageperron** [comment]
This issue is update as we rather need a Cake compatible forum now.
