### ISSUE TITLE
cdli tablet

### ISSUE THREAD

**Issue by englundrk** [cdli-gh/Framework#43]
#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/Framework/

**Comment by englundrk** [comment]
for Prashant: we need to standardize the share notices that go out from iPad or Android versions of cdli tablet so that they contain the basics now in notice from iPad version, but with links to both app store and to Google Store.

**Comment by englundrk** [comment]
Hey,

Why closed? The matter of including a thumbnail with the Android announcement was not resolved.

Bob

**Comment by epageperron** [comment]
Sorry I thought from the recent e-mail exchange that the Android app was in it's final state!

**Comment by epageperron** [comment]
@starlordphr are you on this?

**Comment by epageperron** [comment]
Opening a new issue to put in backlog about this specific thumbnail sub-issue

**Comment by englundrk** [comment]
As follower? Yes, now.

**Comment by starlordphr** [comment]
Sorry, I wasn't active on github for a while. Yeah I know about the final state for the cdli tablet on Android.
