### ISSUE TITLE
Convert EPS to SVG

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/Framework#46]
## Summary

Convert the EPS files we have to SVG
Display SVG images along other artifact images

----------

- Find a command line tool that properly handles the conversion of EPS to SVG without weird intermediary conversion to bitmap and that creates a true SVG output.

- Prepare a one liner to process a folder of eps files

#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/Framework/

**Comment by jayanthjaiswal** [comment]
[pstoedit](http://www.pstoedit.net/) seems to be the way to go.  It description is "Converting Postscript (PS) or PDF files to editable vector graphics (VGs) "
Mac Install:
https://brewinstall.org/Install-pstoedit-on-Mac-with-Brew/
One line command for converting :
```
for EPS in *.eps ; do FIG=`echo "$EPS" | sed -e s/eps$/fig/` ; SVG=`echo "$EPS" | sed -e s/eps$/svg/` ; echo "Converting ... $EPS" ; pstoedit "$EPS" -f fig "$FIG" ; fig2dev -L svg "$FIG" folder_svg/"$SVG" ; rm -f "$FIG" ; done
```
Reference
http://notjustlinux.blogspot.com/2009/05/eps-to-svg.html
Other relevant link:
http://www.mmtek.com/dp20090929/node/78

**Comment by epageperron** [comment]
@englundrk

**Comment by englundrk** [comment]
The conversion would not be the pressing issue for now; I would struggle to see the need to run through bitmapping and revectorization. Note that there is already a folder "svg" in /dl with 260 files to test the I think more difficult matter of the renderer. That would want to either allow user to expand or swish out size of the offered svg line art, or to hard define a rendering resolution that might be something like 4x enlargement of original. svg files in CDLI should be restricted to _l.svg and _ld.svg. They as a rule were processed to lead _l.tif files and thus the primary purpose of this addition would be to make them individually downloadable (aside from svg online renderings being much superior to their rasterized cousins).

**Comment by epageperron** [comment]
https://gitlab.com/cdli/framework/issues/124
