### ISSUE TITLE
Refactoring/slimming framework code repository for containerization

### ISSUE THREAD

**Issue by nomoon** [cdli-gh/Framework#58]
## Summary

Our first attempt to commit the framework codebase to a git resulted in a multi-gigabyte repository containing a lot of legacy and unused files. As a result, and in order to streamline the process of code updates and deployment, we need to refactor and slim this down to a much more manageable size. This also affords us the opportunity to re-organize things for future versions and major updates/additions to parts of the code. It may be desirable to revise this structure or to further refactor different parts into their own repositories.

In this issue, I propose a new file layout and solicit feedback on how this may affect other tools in the system so that it might be revised to minimize issues. The end result will be a new framework repository (or set of several separate repositories) that can be used for docker and ongoing development.

### Proposed file tree

- `app`: Web applications and tools root folder
  - `common`: Common application files, such as database credentials
  - `drupal`: The current Drupal 7 codebase.
    - `file -> ../../webroot/file`: symbolic link to the Drupal static files folder *(this is required due to a quirk of Drupal 7's filesystem configuration)*
    - `file_private`: private Drupal files folder
    - `includes`: Drupal PHP includes
    - `misc`: Drupal misc files
    - `modules`: Drupal modules/plugins
    - `profiles`: Drupal install profiles
    - `sites`: Drupal sites, site themes, configuration
    - `themes`: Drupal global theme data
  - `search`: Search/catalogue code.
  - `upload`: Upload tool code
- `webroot`: Public static files root folder
  - `assets`: Non-Drupal web assets
    - `css`: Static CSS assets
    - `js`: Static JavaScript assets
  - `bulk_data`: CDLI bulk data *(not committed to repository)*
  - `dl`: CDLI artifact images *(not committed to repository)*
  - `file`: Actual location of Drupal static files
  - `images`: Static image assets
  - `pubs`: CDLI publication documents/PDFs
  - `search`: *(publically-inaccessible stub folder, see below)*
  - `tools`: Simple web-accessible tools

### How these folders operate

When a user accesses the CDLI webserver, the following ordered process occurs:

* Specified path matches (such as `/?q=drupal-page` for Drupal content, `/(misc|modules|sites|themes)/...` for Drupal assets, or `/search/...` for the CDLI search interface) are directed to specified locations in the `app` folder tree *if the requested resource exists*.
* Otherwise, files inside the `webroot` folder are served directly by the webserver from `/[dir/file]` *if the requested resource exists*. Note: Server-side code files (e.g. PHP files) in `webroot` are **never** executed.
* Otherwise, the request is directed to the Drupal application. This allows for Drupal "pretty URIs" like `httpx://cdlidomain/associates-staff` rather than `httpx://cdlidomain/?q=associates-staff` and also Drupal-formatted "file not found" error pages.

## Implementation work / Request for feedback

Implementing this requires a number of minor changes to various code files to fix path issues, but many of these parts of the code already needed to be modified to work in the new containerized environment anyway. Once we settle on the filesystem scheme, this process is straightforward.

While I have currently only noted it in two places (`webroot/bulk_data` and `webroot/dl`), it may be prudent to leave more folders of static data outside the git repository. This depends mostly on two things:
  * Size of data -- smaller files are less of an issue to track in git.
  * Frequency of updates/changes -- if static folder contents are modified as a consequence of web activity or running the apps rather than editing/updating the app code, they should probably be separated

Since there are a variety of different CLI tools and in-development web applications that will slot into this new structure and require access to the database and certain static file folders, I would like to know any immediate concerns or questions this new structure suggests for you.

Any separable related issues to this are, of course, welcome.

#### 📈 Progress (0-1): 0.2

See Gantt: http://cdli-dev.org/gantt/Framework/

**Comment by nomoon** [comment]
Sorting out this issue doesn't strictly block our ability to deploy and test some containers on the new VMs, but depending on how substantially the final form changes from this proposal, we may have to "blow up" more or fewer things on the dev VMs between now and release.

cc: @epageperron

**Comment by epageperron** [comment]
Beautiful !!!

I think there is more than one folder in which pubs are located, I think we will have to make sure Drupal upload the publications to the right folder and put in place redirects from the current location to this new consolidated folder.

Also we have css files all over the place, do you want to leave them as is for now (we won't be updating them until Framework anyways, except in the case of incompatibility issues raised by a new browser version or something of the like, and then for the cakephp search we'll have everything in assets?

This is a non issue but can we call file "files" in the plural?

**Comment by nomoon** [comment]
#### Re: Publications

There are two places where pubs are located: `webroot/pubs` and `webroot/file/publications`. The former is a collection of HTML files, CSS, and PDFs, while the latter is just PDF uploads through Drupal. Since the current Drupal setup expects to point links either to `/pubs/something` or `/file/publications/something.pdf` these both still work as-is in the new refactor.

#### Re: CSS/JS/Image Assets
We *could* move existing CSS/JS files around, but that may be more trouble than it's worth. For new work, it would make the most sense to keep such assets in the webroot `/assets/js` and `/assets/css` and either `/assets/images` or just `/images`. That's generally standard for many different web frameworks.

#### Re: Drupal public file folder
* Drupal allows us to specify a relative path to save files to (i.e. `../../webroot/files`), but it generates HTML links to those files simply by dropping the `..` portion, which causes a bunch of problems—suddenly all the links point to something like `href="/webroot/file/my_uploaded_file"`. This is why it's currently set to `./file` and the symbolic link set-up for that folder name in the wrbroot (so it will generate links as `href="/file/my_file` which point to the right location for web access).
 * We *could* change the Drupal public files folder name from `./file/`. However, every currently uploaded public file tracked by Drupal has the `/file/` path hardcoded into its entry in the database. Changing the name to something like `/drupal_public/` would mean we'd need to update the database. Otherwise, all links to previously-uploaded files will still point to `/file/something` and break.

**Comment by epageperron** [comment]
the cdln (cuneiform digital library notes) periodical php code is in /pubs/cdln/php at this time. It will be part of drupal in the next iteration

**Comment by nomoon** [comment]
After talking with @epageperron it seems like we've mostly settled on a layout and workflow.

### Updated folder structure (2018-03-02)
`/ ` : Repo root *(mounted as `/srv` in Docker container filesystem)*
`+-- app ` : Web applications and tools *(live code, served at specified routes)*
`|   +-- common ` : Common/shared application file
`|   +-- cdln ` : CDLN periodical *(?, since it requires PHP)*
`|   +-- drupal ` : The current Drupal 7 codebase.
`|   |   +-- (file) ` : *(`/webroot/file` mounted here in Docker container)*
`|   |   +-- (file_private) ` : *(`/private/drupal` mounted here in Docker container)*
`|   |   \-- ... ` : *(additional Drupal 7 folders)*
`|   +-- search ` : Search/catalogue code
`|   +-- upload ` : Upload tool code
`|   \-- ...` : *(additional apps)*
`+-- private ` : Private static files.
`|   +-- drupal ` : Drupal 7 private files *(see `/app/drupal/file_private`)*.
`|   \-- ... ` : *(additional private files)*
`\-- webroot ` : Public static files *(no server-side code; served by webserver as default `/`)*
`    +-- assets ` : Non-Drupal web assets *(`css/`, `js/`, etc.)*
`    +-- bulk_data ` : CDLI bulk data *(stub; not committed to repo)*
`    +-- dl ` : CDLI artifact images *(stub; not committed to repo)*
`    +-- file ` : Drupal 7 public files *(see `/app/drupal/file`)*
`    +-- images ` : Static image assets
`    +-- pubs ` : Static CDLI publication documents/PDFS
`    +-- tools ` : Simple web-accessible tools
`    \-- ... ` : *(additional static files, some not committed to repo)*

### Repository management notes
* All the apps will share one repository.
* All development on individual apps should happen inside a Git branch called `feature/[app]` or `feature/[app]/[description]`. These branches are unprotected and can be modified by anyone with "Developer" access to the repository.
* Only people with "Master" repository access will be able merge/push to the `develop` and `master` branches. They will handle merging in updates from the app branches and tagging for deployment.

### App containerization notes
* Every app in the `/app` folder will run in its own Docker container.
* Each app container will follow the same filesystem layout, but internally will only contain/have access to appropriate relevant folders *(i.e. every container should see at least `/app/common/` and `/app/[myapp]/`)*.
* Since the user-facing webserver container (nginx) handles static assets, most containers should not need to see `/private/` or `/webroot/`. Even in the example case of the Drupal 7 app, we mount the `/private/drupal/` and `/webroot/file/` folders to the `/app/drupal/[file|file_private/` locations that the app expects. In sum, app containers shouldn't have access to files and paths they don't need to use.
* Developers will be able to work on individual apps on their local machines using Docker Compose. This will set up a virtual set of infrastructure containers (nginx, mariadb, etc) that mirror the configuration of the live servers while allowing developers to edit app source files directly without needing to build/rebuild container images.

### Final thoughts/questions
* Is my placing of CDLN in apps the correct decision?
* Anyone see any issues or have any questions?

**Comment by epageperron** [comment]
CDLN : fine ! 
No additional questions ! :) Maybe Jayanth would have some comments but it looks pretty solid to me

**Comment by epageperron** [comment]
Is this issue done ?

**Comment by nomoon** [comment]
I think so. There are some changes to this scheme but I'll update them in the READMEs once they're finalized.
