### ISSUE TITLE
Collection script updated to work with the NAS

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/Framework#60]
## Summary
We are switching to a NAS to store our archival data. The collections script must be modified to handle this change. The collection's script purpose is to offer museum staff to download the high resolution version of the images of their collections. These images are not accessible on the website and are stored on our archival server.

## Details
*Current workflow: *
User logs in, search for artifacts from the collection they ave privilege with, click on "download archival files", a hi-res image bundle is created on archival/154 for the user. When the archive is ready, an e-mail is sent to the user with the link to their file which is served through crushFTP server directly from 154.

*New workflow: *
First part stays the same, as such the php and python scripts can be reused: 
https://gitlab.com/cdli/framework_pre_virt/blob/uclaprod/cdli/search/download_archival_images.php
https://gitlab.com/cdli/framework_pre_virt/blob/uclaprod/cdli/scripts/copy_image_files.py
The second part changes: The file bundle(s) should be served directly from the web server/156/prod and only to a login user that has the appropriate rights.

#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/Framework/

**Comment by nomoon** [comment]
Regarding the solution we've come to with the workflow of this, I've formalized the internal `app_search` configuration and pushed a [new commit](https://gitlab.com/cdli/framework/commit/499bce76c026e58a0220674420413e115fc7d347) to the `develop` branch of cdli_framework to assist in testing.

Inside the `app_search` container, the read-only `cdli_archivalfiles_new` mount is located at `/mnt/cdli_archivalfiles_new` and the read-write Docker data volume for storing the collections files is located at `/mnt/cdli_collections`.

In the development environment—where we don't have access to the QNAP mount—I've mounted the `dev/stubs/cdli_archivalfiles_new` folder in place of the production mount location. You can replicate any file/folder structure in there that may be necessary to test that the collections script works (such as a subset of artifact images that you want to test the script collecting and zipping).

**Comment by nomoon** [comment]
I'm happy to do some testing, updating, and troubleshooting on this if @Douglasli is away for a bit. I just want to confirm that the `feature/collections` branch has the current state of progress on this feature.
