### ISSUE TITLE
Contribution through Summer of Code

### ISSUE THREAD

**Issue by spaceVStab** [cdli-gh/Framework#67]
Hey
I have been practicing Computer Vision and Machine Learning for a year now. I am interested to contribute in the project, **Computer vision challenge for the cuneiform script** from the idea page. Although I have emailed cdli@ucla.edu, no reply had come. Let me know where do I get started from. 
Thank you

**Comment by epageperron** [comment]
Hi @spaceVStab! To be honest, even with our army of mentors, we have been overwhelmed with the demand. I will add you to your CSoC Slack where you can find answers to some questions and have a better access to mentors.

**Comment by spaceVStab** [comment]
Thanks @epageperron.
I will look forward to contributing my bit as much as possible.
