### ISSUE TITLE
bulk data on gitlab

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/Framework#68]
Create a public repository on Gitlab and have the bulk data dump be copied there daily instead of Github so we can keep the files unsegmented (Github restricts the size of files).

**Comment by nomoon** [comment]
Depending on the size of the bulk data files, I might suggest against using git, or at least suggest using git lfs to store the files (gitlab supports this directly)

**Comment by nomoon** [comment]
Generally, lots of files over 2-20mb (depending on who you ask) will cause friction with Git. We've ignored this in the framework repository with the Drupal 7 static files and publications for now (only around 200mb total IIRC) but im general should avoid large files when possible.

**Comment by epageperron** [comment]
git lfs sounds great ! Let's use it.

**Comment by epageperron** [comment]
https://gitlab.com/cdli/framework/issues/110
