### ISSUE TITLE
Upload functionality

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/Framework#70]
## Summary

The upload python script is employed when an editor uploads an ATF file to the server. The script parses the file so it can be processed in multi-thread. This scripts outputs logs and temporary files while working.

After @nomoon has installed Python in the appropriate container, test the upload functionality and modify as required so it works properly and so it doesn't leave files everywhere.

#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/Framework/

**Comment by nomoon** [comment]
This should probably be tested by several people but appears to be working on my end in the dev environment in the `develop` branch and on the staging server.

**Comment by epageperron** [comment]
Fixed & Tested  August 27 by @nomoon
