### ISSUE TITLE
Full catalogue update from FMPro script.

### ISSUE THREAD

**Issue by nomoon** [cdli-gh/Framework#76]
## Summary

Port current Perl script that updates the CDLI database from an FMPro dump to work on the Docker-based CDLI system. There is a challenge to consider differences in user workflow, since the new CDLI system operates on a VM with no GUI and much more compartmentalized services.

TODOs:
- [x] Investigate current script process.
- [x] Discuss necessary changes to workflow.
- [x] Port/modify script.
- [x] Test.
- [ ] Add "catupdate" command to the deployment CLI.
- [ ]  Implement a cron that will run the catupdate daily.

#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/Framework/

**Comment by nomoon** [comment]
I've successfully run the script in the development environment with minimal changes. I'll implement a "catupdate" command in the deploy CLI that will let authenticated users run the script in the Docker MariaDB environment.

**Comment by epageperron** [comment]
How and where should we put the cat file in the VM network? At this time, a human must manually export the data from FM and upload it manually to 156/core

**Comment by epageperron** [comment]
We are so close !!! :D

**Comment by nomoon** [comment]
@epageperron Ideally the user would run the catupdate command from any internet-connected machine that has the deployment tools (with credentials) and cat file locally on it. The deploy tools are a small repository requiring a recent version of Python (3.6+) and Docker (though it can just be the basic Docker CLI with nothing running).

**Comment by epageperron** [comment]
Sounds perfect.
