### ISSUE TITLE
Add processing for separating Comment, Structure, and the Translation from Transliteration

### ISSUE THREAD

**Issue by Douglasli** [cdli-gh/Framework#78]
## Summary
In order to speed up search, we need to create new fields for Comment, Structure, and Translation, in which data should be added from processing the transliteration field on add, and edit/update. This processing should be done in the model, in the pre-processing method. 

## Other links or relevant information

- [ ] Add a function beforeSave when editing an artifact inscription
- [ ] Extract transliteration without line number to transliteration_clean
- [ ] Extract structure to structure field
- [ ] Extract translations to structure field
- [ ] Extract transcription to structure field
- [ ] Process transliteration_clean and change sign readings for sign name

#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/Framework/

**Comment by epageperron** [comment]
I think this is the one?
in "Table" Class

beforeSave(Event $event, EntityInterface $entity, ArrayObject $options) Fired before each entity is saved. Stopping this event will abort the save operation. When the event is stopped the result of the event will be returned.

**Comment by epageperron** [comment]
We also need to convert transliteration lines sign readings to sign names in another field.

**Comment by epageperron** [comment]
https://gitlab.com/cdli/framework/issues/120
