### ISSUE TITLE
Finish up the data conversion and script for the new database schema

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/Framework#80]
This issue concerns:
- The creation of the new database schema for the CDLI
- The preparation of conversion scripts (with some manual edition) to the new schema
- The conversion of the data to the new model, now and just when we switch to production with the new framework

## Ongoing tasks:
- [ ] **external resources** https://drive.google.com/drive/folders/1Yece5qtEg0AI8qr0VAPaIVOW6n9EahCp
- [ ] Fill all the **credits** 
    - [x] remove the contributor table
    - [x] add a author_id field to the users table
    - [x] all users should have an author entry (list sent by email to @kbabu105) 
    - [x] in the inscriptions table, change user_id to created_by and link with author_id of user
    - [x] in the inscriptions table, change credit_id to credit_to and link with author_id of user
    - [x] in the artifacts table, atf_source, db_source and cdli_collation should take an author id
       - [ ] make an audit of the content as some of the entries seem to have a date and an institution. We might have to create more fields to manage this data ( eg author_id, date, institution). 
    - [x] Convert credits to the new format
    - [x] create credits table (for updates to the catalogue) fields : id, artifact_id, author_id, date, comments

## To do : 
- [x] update artifacts_publications table: remove all "is" fields and add a field type enum "publication_type" and add in the enum "primary, history, citation, collation, other"
- [x] make update publications.bibliography field name to "bibtexkey"
- [x] add a field called designation in publications
- [x] update conversion script : 
    - [x] put prime pub content in designation instead of bibliography and
    - [x] do not add any entries with the keywords "unpublished" and "unassigned"
- [x] What's artifacts.surface_comments for? Is we can't find out, delete, it's empty in the new db  https://docs.google.com/spreadsheets/d/17cZKVEulE6f5B3Yi_d4lSbLiOX241N-FA4juK7uwX8M/edit#gid=0
- [ ] fill artifacts.'is_school_text" field based on the genre table in google docs
- [x] change field users.creator to users.created_by
- [x] create archives table and fill artifacts.archive_id  based on cataloguesnew.dumb
- [x] also add archives and archive_id in artifacts based on csv file sent by @epageperron
- [ ] fill collections.geo_coordinates cross referencing collections from cataloguesnew.google_earth_collection
- [x]  remove artifacts.electronic_publication field;
- [x] Add current cataloguesnew.electronic_publication data to publications (only fill the url field with the data and the entry type id with id for 'other' ); link with artifacts in artifacts_publications using the "other" field for enum. 
- [ ] artifacts.cdli_collation is a credit field, so add credit type cdli_collation in the enum for credit_type and convert to ids. 
- [ ] I think publications of artifacts have been merged with publications refereed to in the cdli notes. This is fine, although, we are missing the artifacts_publications data, the publication type according to cdli (primary, history/secondary, citation) - let's have a chat about pubs?
- [x] Add a password field in the user table (without any data in)
- [ ] Adapt the schema to host Rune Rattenborg's geo data
- [ ] Artifact type needs work: Add "composite"; @epageperron should finish up sorting the 800 subtypes .  https://docs.google.com/document/d/1pSu3xWB2pZK53hTHLt_zgT1I8OZvbBVTjYA-k-FokYA/edit?usp=drive_web&ouid=106167595571896896527 
- [ ] Remove all temporal tables from the new model (tables: accounting_periods, months, years, fields : artifacts.accounting_period .alternative_years)
- [ ] Merge @sengarsameer's temporal tables and data with the general schema (https://github.com/cdli-gh/database-schema)

## Done tasks:
- [x] artifacts.seal_no and artifacts.composite_no fields should contain the Q or S number from the cataloguesnew.designation field and only if the artifact is indeed the seal or the composite entry
          Example : 
            Designation of a composite text: "CDLI Lexical 000012 (ED Animals A) composite"
            Designation of a seal : "CDLI Seals 000478 (composite)" or " CDLI Seals 000768 (physical)"
 - [x] Fill artifacts_seals
 - [x] Fill artifacts_composites (It's already filled, make sure it contains only a list of artifacts that are witnesses of composites)
- [x] Associate regions with proveniences https://docs.google.com/document/d/1T-5qqaPiFbSdFr9IFKVMRT2_hpdZx44xpIxalkvxLsE/edit
- [x] add a "weight" field to the artifacts table
- [x] Clean up the collections table (still duplicated and multiple collections in some entries)
- [x] Add a "private" flag for collections and remove "private" from collections names
- [x] Create a field collections.slug and postings.slug
- [x] Integrate version history table data into the inscriptions table (with "is_latest" flag off)
- [x] remove password hashes and collections passwords from the users table and create an email field
- [x] Remove artifacts.month_id, month_no, day_no fields
- [x] fill artifacts.height, thickness and width with mm sizes
- [x]  fill artifacts.created with cataloguesnew.date_entered, and artifacts.modified with cataloguesnew.date_updated

#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/Framework/

**Comment by epageperron** [comment]
For me (From Drupal) : 
- [ ] Convert news
- [ ] Convert pages
- [ ] Convert cdli publications

**Comment by epageperron** [comment]
@sengarsameer Please add your remaining todo to finish up the model and the data conversion and insertion here

**Comment by sengarsameer** [comment]
For me:

- [ ] Handle the dates table
- [ ] Merged the year and month schema, and associate them with the artifacts
- [ ] Convert the data we have in the current cdli database in the date fields into the new format by a script.

**Comment by epageperron** [comment]
@kbabu105 had a great idea, for the collections table, let's have a is_private field and flag 1 for private collections and remove "private:"

**Comment by epageperron** [comment]
Here is how I suggest to resolve the credits question : 
remove the contributor table
add a user_id field to the authors table
all users should have an author entry

in the inscriptions table, change user_id to created_by and link with author table
in the inscriptions table, change credit_id to credit_to and link with author table

in the artifacts table, atf_source, db_source and cdli_collation should take an author id but we have to make an audit of the content as some of the entries seem to have a date and an institution. We might have to create more field to manage this data. Add a "created_by" field. 

the credits table will be used for updates to the catalogue
fields : id, artifact_id, author_id, date, comments

**Comment by epageperron** [comment]
- [ ] Krishna send updated version of db to @greek-geek  and @epageperron
- [ ] EPP send list of authors matches to users

**Comment by epageperron** [comment]
Add to the doc: when checking ETCSL entries "check", add the proper version to the external resources for the concerned artifact

**Comment by epageperron** [comment]
https://gitlab.com/cdli/framework/issues/116
