### ISSUE TITLE
Website design edit

### ISSUE THREAD

**Issue by cleanandclare** [cdli-gh/Framework#84]
## Summary

@epageperron I have uploaded the web design pdf in google docs folder(which I will also leave a link below). Please take a look and comment anything that needs to be improved or removed. Especially for the single item result page, I have made modifications to the mockup that was provided because alot of the categories were not relevant anymore according to https://cdli.ucla.edu/search/search_results.php?SearchMode=Text&ObjectID=P285640

## Other links or relevant information

this is the link to the google docs : https://drive.google.com/file/d/1y4BT-1--hol0iU9Tu6x41099LZgapDNl/view?usp=sharing

**Comment by epageperron** [comment]
Points of discussion : 

- [ ] Maybe we could change the color of blocks using Aman's grey scale instead of solid borders to highlight divs?

- [ ] Logo should probably be updated

- [ ] Let's look at the new DB schema (which wasn't as completed as now when Aman worked on the wireframe) to see what the categories and their data looks like 

- [ ] Let's look at the old and new information maps of the site to decide how and where the main menu links should appear

**Comment by epageperron** [comment]
For me : 
- [ ] Make a list of important categories for summary 
- [ ] Send new db to Clare 
- [ ] Find the menus documents
- [ ] List of categories
- [ ] Templates for information pages

**Comment by epageperron** [comment]
We will have to add a credits section in the single object view. There are a bunch of credit types, we can go though them once we have a fresh copy of the db from @kbabu105

**Comment by cleanandclare** [comment]
provenience : https://docs.google.com/document/d/1T-5qqaPiFbSdFr9IFKVMRT2_hpdZx44xpIxalkvxLsE/edit

**Comment by cleanandclare** [comment]
left to do:

- [ ] complete single page view (new db)
- [ ] modify search result according to the first one we worked on together
- [ ] compact view - look at genre, periods, provenience etc https://docs.google.com/document/d/1T-5qqaPiFbSdFr9IFKVMRT2_hpdZx44xpIxalkvxLsE/edit
- [ ] keep working on the logo
- [ ] sponsors image copy and paste to footer
- [ ] fix the menu to other pages like the first page

**Comment by epageperron** [comment]
icons for download and print #85

**Comment by cleanandclare** [comment]
@epageperron please upload logos here :)

**Comment by epageperron** [comment]
NSF : 
https://www.google.ca/search?q=nsf&rlz=1C5CHFA_enCA761CA761&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiasaSuw7_cAhUM6IMKHVckCvcQ_AUICigB&biw=1394&bih=716

NEH : 
https://www.google.ca/search?rlz=1C5CHFA_enCA761CA761&biw=1394&bih=716&tbm=isch&sa=1&ei=1jBbW8_SOuz4jwToibOQDQ&q=neh&oq=neh&gs_l=img.3..0l10.13724.13929.0.14675.3.3.0.0.0.0.87.238.3.3.0....0...1c.1.64.img..0.3.238...0i67k1.0.wkc_nGXy-PE

SSHRC:
https://www.google.ca/search?rlz=1C5CHFA_enCA761CA761&biw=1394&bih=716&tbm=isch&sa=1&ei=6DBbW4meFMHqjwSO1YbYDA&q=sshrc&oq=sshrc&gs_l=img.3..0l2j0i24k1l8.15807.16348.0.16453.5.5.0.0.0.0.96.416.5.5.0....0...1c.1.64.img..0.5.416...0i10k1.0.oy_4mQfJhhA

Mellon : https://www.google.ca/search?rlz=1C5CHFA_enCA761CA761&biw=1394&bih=716&tbm=isch&sa=1&ei=CDFbW5-KIOmLjwSEj6R4&q=mellon+foundation+logo&oq=mellon+foundation+logo&gs_l=img.3..0j0i5i30k1l3.4242.5020.0.5216.5.5.0.0.0.0.125.449.4j1.5.0....0...1c.1.64.img..0.5.448...0i30k1.0.CquxwI1k3cs

IMLS : https://www.google.ca/search?rlz=1C5CHFA_enCA761CA761&biw=1394&bih=716&tbm=isch&sa=1&ei=GTFbW5WcLoOHjwTJwq5A&q=imls+logo&oq=imls+logo&gs_l=img.3..0.1995.2497.0.2654.5.5.0.0.0.0.120.461.3j2.5.0....0...1c.1.64.img..0.5.459...0i30k1j0i8i30k1j0i24k1.0.Qp-DErY9Jcs

MPIWG : 
https://www.google.ca/search?rlz=1C5CHFA_enCA761CA761&biw=1394&bih=716&tbm=isch&sa=1&ei=MzFbW_b9BcfMjwThv5yYDw&q=max+planck+institute+logo&oq=max+planck+institute+logo&gs_l=img.3..0.3307.3471.0.3785.2.2.0.0.0.0.82.154.2.2.0....0...1c.1.64.img..0.2.154....0.n_wHkOiscYI

Oxford : 
https://www.google.ca/search?rlz=1C5CHFA_enCA761CA761&biw=1394&bih=716&tbm=isch&sa=1&ei=SDFbW4ePLKbNjwTE_aLYCA&q=oxford+university+logo&oq=oxford+university+logo&gs_l=img.3..0l10.1627.2197.0.2369.5.4.0.1.1.0.91.339.4.4.0....0...1c.1.64.img..0.5.342...0i67k1.0.Nvygd_QeoBY

UCLA : https://www.google.ca/search?rlz=1C5CHFA_enCA761CA761&biw=1394&bih=716&tbm=isch&sa=1&ei=TDFbW9unEZmjjwSIsInoDQ&q=ucla+logo&oq=ucla+logo&gs_l=img.3..0l2j0i67k1j0j0i67k1j0l5.13618.18796.0.18948.19.14.4.1.1.0.133.1140.8j4.12.0....0...1c.1.64.img..2.17.1163.0...0.fdxWnUaEn0I

CC : 
https://www.google.ca/search?rlz=1C5CHFA_enCA761CA761&biw=1394&bih=716&tbm=isch&sa=1&ei=cDFbW9TMC4f7jwS4mIvwBw&q=compute+canada+logo&oq=compute+canada+logo&gs_l=img.3..0.2102.2652.0.2847.5.3.0.2.2.0.98.277.3.3.0....0...1c.1.64.img..0.5.284...0i30k1j0i24k1.0.zq1Hj25gWDQ

**Comment by epageperron** [comment]
CDH logo : 
 https://www.google.ca/search?rlz=1C5CHFA_enCA761CA761&biw=1394&bih=716&tbm=isch&sa=1&ei=czFbW9LrNKG_jwSD2KC4AQ&q=center+for+digital+humanities+ucla+logo&oq=center+for+digital+humanities+ucla+logo&gs_l=img.3...306746.312325.0.312524.39.26.0.13.13.0.137.2286.16j8.24.0....0...1c.1.64.img..2.32.1847...0j0i67k1j0i30k1j0i24k1.0.5CGmd_28Ckc

**Comment by epageperron** [comment]
@cleanandclare now in coding phase this issue gets closed :-)
