### ISSUE TITLE
Download and Print search results

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/Framework#85]
Add a link to generate pdf and download for printing of search results on the main page, single page and the most important: compact view.

Add a link to download the data in other formats

Options should be available on which data to download ( catalogue data, image, transcription..

**Comment by veer11997** [comment]
@epageperron i want to contribute on the project .so will you update me so i will work on it.

**Comment by epageperron** [comment]
https://gitlab.com/cdli/framework/issues/100
