### ISSUE TITLE
Authentication and access system

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/Framework#9]
- [x] Install an authentication and access module for Cakephp that uses MFA
- [ ] Create the access levels and double check the users
- [ ] Document how to implement access check

**Comment by epageperron** [comment]
dependent on initial cake+drupal setup. Will notify when ready

**Comment by epageperron** [comment]
Please update on status

**Comment by Douglasli** [comment]
Finish the authentication and access module for Cakephp that uses MFA.
Working on the access levels.

**Comment by epageperron** [comment]
https://gitlab.com/cdli/framework/issues/84
