### ISSUE TITLE
Update login form with SVG avatar that responds to input

### ISSUE THREAD

**Issue by amaaniqbal** [cdli-gh/Framework#97]
## Summary

Update the login form with a creative SVG avatar that responds to the inputs being typed.

## Other links or relevant information

CodePen Link: https://codepen.io/dsenneff/full/2c3e5bc86b372d5424b00edaf4990173

#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/Framework/

**Comment by rillian** [comment]
That codepen is awesome! Can you make it look like one of [these people](https://wtfarthistory.com/post/43985624315/what-big-eyes-you-have)?

**Comment by amaaniqbal** [comment]
I guess the basic SVG is constructed using Illustrator with which I am unfamiliar so far. I will definitely try if I could get some assistance with SVG construction later. 

For now, I will try to figure out if such SVG can be generated using D3.js

**Comment by epageperron** [comment]
https://gitlab.com/cdli/framework/issues/85
