### ISSUE TITLE
i think if we want to do analysis of any statue or monuments than there we use one more funtionality like 3D  image analysis like x,y,z in 3 dimension make statue in 3d dimensions

### ISSUE THREAD

**Issue by shubham9455999082** [cdli-gh/Framework#98]
#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/Framework/

**Comment by Deepak-Sati** [comment]
@shubham9455999082 can we use

**Comment by Deepak-Sati** [comment]
@shubham9455999082  
can we use Conda library matplotlib to process image in form of 3d array using numpy in python

**Comment by ALWISH007** [comment]
@shubham9455999082  what could be the possible technologies that we can use to implement this. Any ideas on that.

**Comment by shubham9455999082** [comment]
yes we can improve it and better it

**Comment by shubham9455999082** [comment]
is this project  for the gosc20 if yes than i than i am ready to contribute
and work on this to improve this project

**Comment by shubham9455999082** [comment]
we can use 3d imaging as x, y,z dimenions plotting

**Comment by epageperron** [comment]
Hi Shubam,
We don't use the issue system in this repo, it has been ported to Gitlab. 
Please take a look at this link before opening another issue. https://wiredcraft.com/blog/how-we-write-our-github-issues/ Thanks !
